### ISSUE TITLE
April 2017

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode-chrome-debug#395]
- [x] All Chrome instances are killed if debugging is stopped - https://github.com/Microsoft/vscode-chrome-debug/issues/116
- [x] Enable userDataDir by default - https://github.com/Microsoft/vscode-chrome-debug/issues/210
- [x] Enhancement: Select open tab on start debug - https://github.com/Microsoft/vscode-chrome-debug/issues/280
- [x] Handle create-react-app config out of box - https://github.com/Microsoft/vscode-chrome-debug/issues/315

**Comment by auchenberg** [comment]
All completed. Closing.
